import os
import logging
from odoo import models, fields, api

_logger = logging.getLogger(__name__)


class DaemonKeyRegistry(models.Model):
    _name = "daemon.key.registry"
    _description = "Daemon API Key Registry"

    name = fields.Char(string="Daemon Name", required=True)
    user_id = fields.Many2one(
        "res.users",
        string="Service Account",
        required=True,
        domain=[("is_service_account", "=", True)],
    )
    env_file_path = fields.Char(
        string="Environment File Path",
        required=True,
        help="Absolute path to the protected output directory for this daemon's .env file.",
    )
    last_rotated = fields.Datetime(string="Last Rotated", readonly=True)

    @api.model
    def register_daemon(self, daemon_name, user_xml_id, env_file_path):
        """
        API for other modules to request a bearer token/API key for their daemon.
        This registers the daemon for automated 60-day rotations.
        """
        svc_uid = self.env["zero_sudo.security.utils"]._get_service_uid(user_xml_id)
        user = self.env["res.users"].browse(svc_uid)

        registry = self.env["daemon.key.registry"].search(
            [("name", "=", daemon_name)], limit=1
        )
        if not registry:
            registry = self.env["daemon.key.registry"].create(
                {
                    "name": daemon_name,
                    "user_id": user.id,
                    "env_file_path": env_file_path,
                }
            )
        else:
            registry.write({"user_id": user.id, "env_file_path": env_file_path})

        registry._rotate_key_and_write_file()
        return True

    def _rotate_key_and_write_file(self):
        self.ensure_one()

        # Revoke old keys for this specific service account
        old_keys = self.env["res.users.apikeys"].search(
            [("user_id", "=", self.user_id.id)], limit=100
        )
        old_keys.unlink()

        # Generate new key
        key_description = f"Daemon Vault: {self.name} - {fields.Datetime.now()}"
        raw_key = self.env["res.users.apikeys"]._generate(
            self.user_id.id, key_description
        )

        # Write to secure file
        self._write_secure_env_file(self.env_file_path, self.user_id.login, raw_key)
        self.last_rotated = fields.Datetime.now()
        _logger.info(
            f"Successfully rotated and exported API key for daemon: {self.name}"
        )

    def _write_secure_env_file(self, path, login, key):
        """
        Writes the credentials to the specified path and locks permissions to 0600.
        Creates directories with 0700 if they do not exist.
        """
        directory = os.path.dirname(path)
        if not os.path.exists(directory):
            os.makedirs(directory, mode=0o700, exist_ok=True)

        with open(path, "w") as f:
            f.write("# Auto-generated by daemon.key.registry\n")
            f.write(f"ODOO_RPC_LOGIN={login}\n")
            f.write(f"ODOO_RPC_KEY={key}\n")

        os.chmod(path, 0o600)

    @api.model
    def _cron_rotate_all_keys(self):
        """
        Executes via ir.cron. Rotates keys for all registered daemons.
        Uses stateless batching and programmatic re-triggering.
        """
        import datetime

        threshold = fields.Datetime.now() - datetime.timedelta(days=59)
        registries = self.env["daemon.key.registry"].search(
            ["|", ("last_rotated", "=", False), ("last_rotated", "<", threshold)],
            limit=10,
        )

        for reg in registries:
            reg._rotate_key_and_write_file()
            self.env.cr.commit()

        if len(registries) == 10:
            self.env.ref("daemon_key_manager.ir_cron_rotate_daemon_keys")._trigger()
