# -*- coding: utf-8 -*-
import glob
import logging
import os
import pwd
import shutil
import signal
import time
import urllib.request
import threading
from unittest.mock import MagicMock, patch
from odoo.tests.common import HttpCase, TransactionCase, ChromeBrowser

_logger = logging.getLogger(__name__)

class TourWatchdogError(Exception):
    pass

def _timeout_handler(signum, frame):
    signal.signal(signum, signal.SIG_IGN) # Debounce
    _logger.error("TRACING: OS Signal %s (Timeout) received! Force-aborting hung thread.", signum)
    raise TourWatchdogError(f"Test step timed out and was aborted by OS signal {signum}.")

# 🚨 BENIGN ERROR SCRUBBER 🚨
# Odoo native asserts console errors during browser.stop().
# We intercept this to silently purge expected warnings (like Owl dev mode)
# so they don't falsely fail the test suite.
original_browser_stop = ChromeBrowser.stop
def _patched_browser_stop(self, *args, **kwargs):
    for attr in ['_errors', '_browser_errors', 'errors']:
        if hasattr(self, attr):
            error_list = getattr(self, attr)
            if isinstance(error_list, list):
                filtered = []
                for e in error_list:
                    msg = str(e).lower()
                    if "owl is running in 'dev' mode" in msg or "resizeobserver" in msg:
                        continue
                    filtered.append(e)
                setattr(self, attr, filtered)
    return original_browser_stop(self, *args, **kwargs)
ChromeBrowser.stop = _patched_browser_stop

# 🚨 SYNCHRONOUS DOM & SCREENSHOT DUMP 🚨
# Kept strictly for normal test failures (e.g. missing elements).
# We explicitly avoid invoking this when a hard deadlock is detected.
original_take_screenshot = ChromeBrowser.take_screenshot
def _patched_take_screenshot(self, *args, **kwargs):
    _logger.error("\n========== PYTHON-INITIATED UI STATE DUMP ==========")
    try:
        res = self._websocket_request('Runtime.evaluate', params={
            'expression': """
                (() => {
                    function _buildSkeleton(node) {
                        if (!node) return "";
                        if (node.nodeType === Node.TEXT_NODE) return node.textContent.trim();
                        if (node.nodeType !== Node.ELEMENT_NODE) return "";
                        if (node.classList && (node.classList.contains('d-none') || node.classList.contains('o_hidden'))) return "";

                        let isImportant = ['BUTTON', 'INPUT', 'A', 'SELECT', 'TEXTAREA'].includes(node.tagName) ||
                            node.hasAttribute('name') || node.hasAttribute('id') || node.hasAttribute('data-menu-xmlid') ||
                            (node.classList && Array.from(node.classList).some(c => c.startsWith('o_tour_') || c === 'o_notification' || c === 'modal'));

                        let childrenText = Array.from(node.childNodes).map(_buildSkeleton).filter(Boolean).join(' ');

                        if (isImportant) {
                            let attrs = [];
                            ['name', 'id', 'data-menu-xmlid', 'type', 'placeholder', 'value'].forEach(a => {
                                if (node.hasAttribute(a)) attrs.push(a + '="' + node.getAttribute(a) + '"');
                            });
                            if (node.classList) {
                                let cls = Array.from(node.classList).filter(c => c.startsWith('o_') || c === 'btn' || c.startsWith('btn-')).join(' ');
                                if (cls) attrs.push('class="' + cls + '"');
                            }
                            let tag = node.tagName.toLowerCase();
                            let content = childrenText.length > 80 ? childrenText.substring(0, 80) + '...' : childrenText;
                            return '\\n<' + tag + ' ' + attrs.join(' ') + '>' + content + '</' + tag + '>';
                        }
                        return childrenText;
                    }
                    return "URL: " + document.location.pathname + document.location.hash + "\\n" + _buildSkeleton(document.body).replace(/\\s{2,}/g, ' ');
                })();
            """,
            'returnByValue': True
        }, timeout=10.0)
        if res and 'result' in res and 'value' in res['result']:
            _logger.error("========== INTERACTABLE DOM SKELETON ==========\n%s\n===============================================", res['result']['value'])
    except Exception as dump_e: # audit-ignore-catch-all
        _logger.warning("TRACING: Could not request DOM state via CDP: %s", repr(dump_e))

    try:
        path = original_take_screenshot(self, *args, **kwargs)
        # Odoo 19 returns a concurrent.futures.Future for async screenshot dispatch
        if hasattr(path, 'result'):
            path = path.result(timeout=20.0)

        _logger.error("TRACING: Screenshot generated by Chrome at %s", path)

        err_log = os.environ.get("HAMS_REAL_ERROR_LOG")
        if path and os.path.exists(path) and err_log:
            host_tmp = os.path.dirname(err_log)

            # Secure Directory Creation
            is_new_dir = not os.path.exists(host_tmp)
            os.makedirs(host_tmp, exist_ok=True)

            orig_user = os.environ.get("SUDO_USER", "odoo")
            orig_uid, orig_gid = -1, -1
            try:
                user_info = pwd.getpwnam(orig_user)
                orig_uid = user_info.pw_uid
                orig_gid = user_info.pw_gid
                if is_new_dir:
                    os.chown(host_tmp, orig_uid, orig_gid)
            except Exception as user_e: # audit-ignore-catch-all
                _logger.warning("TRACING: Could not resolve SUDO_USER info for chown: %s", repr(user_e))

            dst = os.path.join(host_tmp, os.path.basename(path))
            shutil.copy2(path, dst)
            try:
                if orig_uid != -1:
                    os.chown(dst, orig_uid, orig_gid)
            except Exception as chown_e: # audit-ignore-catch-all
                _logger.warning("TRACING: Could not chown screenshot file: %s", repr(chown_e))

            _logger.error("TRACING: Successfully moved screenshot to host partition: %s", dst)
    except Exception as ss_e: # audit-ignore-catch-all
        _logger.warning("TRACING: Native screenshot failed: %s", repr(ss_e))

ChromeBrowser.take_screenshot = _patched_take_screenshot


class DiagnosticMock(MagicMock):
    def __init__(self, *args, **kwargs):
        max_depth = kwargs.pop("max_recursion_depth", 5)
        super().__init__(*args, **kwargs)
        self._max_depth = max_depth
        self._current_depth = 0

    def __call__(self, *args, **kwargs):
        self._current_depth += 1
        if self._current_depth > self._max_depth:
            self._current_depth = 0
            raise RecursionError(
                f"DiagnosticMock Security Trip: Recursion depth limit ({self._max_depth}) exceeded "
                f"on mock '{self._mock_name or 'unnamed'}'. You likely have a cyclic patch or "
                f"are mocking a core Odoo registry propagation method."
            )
        try:
            return super().__call__(*args, **kwargs)
        finally:
            self._current_depth -= 1


class SafePatchMixin:
    def safe_patch(self, target, *args, **kwargs):
        if not args and "new" not in kwargs and "new_callable" not in kwargs:
            kwargs["new_callable"] = DiagnosticMock
        patcher = patch(target, *args, **kwargs)
        mock_obj = patcher.start()
        self.addCleanup(patcher.stop)
        return mock_obj

    def safe_patch_object(self, target, attribute, *args, **kwargs):
        if not args and "new" not in kwargs and "new_callable" not in kwargs:
            kwargs["new_callable"] = DiagnosticMock
        patcher = patch.object(target, attribute, *args, **kwargs)
        mock_obj = patcher.start()
        self.addCleanup(patcher.stop)
        return mock_obj


class HamsTransactionCase(TransactionCase, SafePatchMixin):
    # [@ANCHOR: hams_transaction_case]
    pass


class HamsHttpCase(HttpCase, SafePatchMixin):
    # [@ANCHOR: hams_http_case]

    @classmethod
    def setUpClass(cls):
        # 🚨 THE ANTI-HANG INJECTION 🚨
        # Odoo's native HttpCase spawns non-daemon threads for Werkzeug and Chrome websockets.
        # If these connections deadlock, the non-daemon threads prevent Python from exiting,
        # causing the entire test runner to hang infinitely.
        # We intercept thread.start() to force EVERY thread spawned during setup to be a daemon.
        original_start = threading.Thread.start

        def _daemonized_start(self_thread, *args, **kwargs):
            self_thread.daemon = True
            return original_start(self_thread, *args, **kwargs)

        with patch.object(threading.Thread, 'start', new=_daemonized_start):
            super().setUpClass()

    @classmethod
    def tearDownClass(cls):
        _logger.info("TRACING: Entering HamsHttpCase.tearDownClass.")

        # Defuse Server Thread Join
        if hasattr(cls, 'server_thread') and cls.server_thread:
            cls.server_thread.join = lambda *args, **kwargs: None

        # Defuse Server Stop
        if hasattr(cls, 'server') and cls.server:
            try:
                if hasattr(cls.server, 'server') and hasattr(cls.server.server, 'socket'):
                    cls.server.server.socket.close()
            except OSError as e:
                _logger.error("TRACING: Ignored OSError closing server socket: %s", e)
            except Exception as e: # audit-ignore-catch-all
                _logger.error("TRACING: Ignored Exception closing server socket: %s", e)
            cls.server.stop = lambda *args, **kwargs: None

        # OS Timeout for super().tearDownClass()
        original_alrm = signal.signal(signal.SIGALRM, _timeout_handler)
        signal.alarm(30)
        try:
            super().tearDownClass()
            _logger.info("TRACING: Successfully completed super().tearDownClass()")
        except Exception as e: # audit-ignore-catch-all
            if "socket is already closed" in str(e) or "WebSocketConnectionClosedException" in type(e).__name__:
                _logger.warning("TRACING: Native tearDownClass encountered closed websocket (expected during abort).")
            else:
                _logger.error("TRACING: Native teardown failed or hung: %s", e)
        finally:
            signal.alarm(0)
            signal.signal(signal.SIGALRM, original_alrm)

            # Aggressively murder Chrome AFTER teardown
            if hasattr(cls, 'browser') and cls.browser:
                if hasattr(cls.browser, 'chrome_process'):
                    try:
                        cls.browser.chrome_process.kill()
                        _logger.info("TRACING: Aggressively killed chrome_process to drop websockets.")
                    except OSError:
                        pass
                # Neutralize browser websocket join
                if hasattr(cls.browser, '_websocket_thread') and cls.browser._websocket_thread:
                    cls.browser._websocket_thread.join = lambda *args, **kwargs: None

            _logger.info("TRACING: Exiting HamsHttpCase.tearDownClass")

    def tearDown(self):
        # Apply OS-level timeout to teardown to prevent unkillable zombies
        _logger.info("TRACING: Entering HamsHttpCase.tearDown")

        original_alrm = signal.signal(signal.SIGALRM, _timeout_handler)
        signal.alarm(60) # 60 seconds hard cap for teardown
        try:
            super().tearDown()
            _logger.info("TRACING: Completed super().tearDown")
        except Exception as e: # audit-ignore-catch-all
            if "socket is already closed" in str(e) or "WebSocketConnectionClosedException" in type(e).__name__ or "BrokenPipeError" in type(e).__name__:
                _logger.warning("TRACING: Native tearDown encountered closed websocket (expected during abort).")
            else:
                _logger.error("TRACING: HamsHttpCase.tearDown caught exception: %s", e)
        finally:
            signal.alarm(0)
            signal.signal(signal.SIGALRM, original_alrm)

            # 🚨 THE PIPE-CLOSING INJECTION 🚨
            # Moved aggressive kill AFTER native teardown so Odoo finishes saving screenshots
            # and extracts code coverage without Chrome dying prematurely.
            if hasattr(self, 'browser') and self.browser:
                if hasattr(self.browser, 'chrome_process'):
                    try:
                        self.browser.chrome_process.kill()
                        _logger.info("TRACING: Aggressively killed instance chrome_process.")
                    except OSError:
                        pass
                if hasattr(self.browser, '_websocket_thread') and self.browser._websocket_thread:
                    self.browser._websocket_thread.join = lambda *args, **kwargs: None

            # Clean up the V8 profiler log to prevent runaway disk usage if the test succeeded
            if not getattr(self.__class__, '_hams_tour_failed', False):
                for log_file in glob.glob("/var/tmp/v8_hang*.log"):
                    try:
                        # Truncate rather than remove. This preserves the file descriptor
                        # so the persistent Chrome instance can safely keep writing to it.
                        with open(log_file, 'w'):
                            pass
                    except OSError:
                        pass

            _logger.info("TRACING: Exiting HamsHttpCase.tearDown")

    def browser_js(self, *args, **kwargs):
        _logger.info("TRACING: Entering browser_js wrapper. Setting 60s SIGALRM.")
        original_alrm = signal.signal(signal.SIGALRM, _timeout_handler)
        signal.alarm(60)
        try:
            super().browser_js(*args, **kwargs)
            _logger.info("TRACING: super().browser_js completed successfully.")
        except Exception as e: # audit-ignore-catch-all
            self.__class__._hams_tour_failed = True

            # Check if this exception chain involves our TourWatchdogError
            # or a websocket closure caused by the reaper/timeout.
            is_watchdog = False
            current_exc = e
            while current_exc is not None:
                if isinstance(current_exc, TourWatchdogError) or "socket is already closed" in str(current_exc) or "BrokenPipeError" in type(current_exc).__name__:
                    is_watchdog = True
                    break
                current_exc = getattr(current_exc, '__context__', None)

            # Only attempt a synchronous screenshot if Chrome is NOT deadlocked
            if not is_watchdog and hasattr(self, 'browser'):
                try:
                    _logger.error("TRACING: Exception caught in browser_js. Forcing screenshot...")
                    self.browser.take_screenshot()
                except Exception as ss_e: # audit-ignore-catch-all
                    _logger.error("TRACING: Forced screenshot failed: %s", repr(ss_e))

            if is_watchdog:
                _logger.error("TRACING: Gracefully caught watchdog timeout or severed websocket. Truncating traceback via from None.")
                raise AssertionError("Tour failed due to watchdog timeout (OS Signal 14) or severed Chrome websocket.") from None
            else:
                _logger.error("TRACING: super().browser_js failed with exception: %s", repr(e))
                raise e from None
        finally:
            signal.alarm(0)
            signal.signal(signal.SIGALRM, original_alrm)
            _logger.info("TRACING: Exiting browser_js wrapper.")

    def start_tour(self, *args, **kwargs):
        _logger.info("TRACING: Entering start_tour wrapper.")
        try:
            super().start_tour(*args, **kwargs)
            _logger.info("TRACING: super().start_tour completed successfully.")
        except Exception as e:  # audit-ignore-catch-all
            self.__class__._hams_tour_failed = True
            _logger.error("\n=== TOUR FAILED OR HUNG. DUMPING COMPILED ASSETS ===")
            try:
                bundle = self.env['ir.qweb']._get_asset_bundle('web.assets_tests').js()
                dump_path = '/var/tmp/failed_tour_bundle.js'
                with open(dump_path, 'w') as f:
                    if isinstance(bundle, str):
                        f.write(bundle)
                    elif hasattr(bundle, 'decode'):
                        f.write(bundle.decode('utf-8'))
                    elif hasattr(bundle, 'raw'):
                        f.write(bundle.raw.decode('utf-8'))
                    else:
                        f.write(str(bundle))
                _logger.error("Dumped compiled JS bundle to %s", dump_path)
            except Exception as inner_e:  # audit-ignore-catch-all
                _logger.error("Could not dump bundle to /var/tmp: %s", repr(inner_e))

            if isinstance(e, AssertionError):
                _logger.error("TRACING: Tour failed cleanly with AssertionError: %s", repr(e))
                raise e from None
            else:
                _logger.error("TRACING: Exception caught in start_tour wrapper: %s", repr(e))
                raise e from None


class HamsIntegrationCase(HamsHttpCase):
    # [@ANCHOR: integration_daemon_testing]

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls._daemons = []

    @classmethod
    def tearDownClass(cls):
        env = cls.env
        daemon_utils = env["zero_sudo.daemon.utils"]
        for process in cls._daemons:
            daemon_utils.stop_daemon_process(process)
        cls._daemons.clear()
        super().tearDownClass()

    @classmethod
    def start_daemon(cls, script_path, args=None, env_vars=None, health_url=None, timeout=600):
        env = cls.env
        daemon_utils = env["zero_sudo.daemon.utils"]
        process = daemon_utils.start_daemon_process(script_path, args, env_vars)
        cls._daemons.append(process)

        if health_url:
            start_time = time.time()
            is_healthy = False
            while time.time() - start_time < timeout:
                if process.poll() is not None:
                    raise RuntimeError(f"FATAL: Daemon process '{script_path}' crashed with exit code {process.returncode} while waiting for health check!")
                try:
                    req = urllib.request.Request(health_url)
                    with urllib.request.urlopen(req, timeout=1.0) as response:
                        if response.getcode() in (200, 204):
                            is_healthy = True
                            break
                except Exception as e: # audit-ignore-catch-all
                    _logger.error("Daemon health check not ready yet: %s", repr(e))
                time.sleep(0.5) # audit-ignore-sleep

            if not is_healthy:
                raise TimeoutError(f"FATAL: Daemon health check for '{script_path}' timed out after {timeout} seconds.")

        return process
