#!/usr/bin/env python3
import os
import sys
import getpass
import secrets
import subprocess
import glob


def load_existing_env(env_path):
    env_vars = {}
    with open(env_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env_vars[k.strip()] = v.strip()
    return env_vars


def prompt_and_generate(env_path):
    try:
        from passlib.context import CryptContext
        from cryptography.fernet import Fernet
    except ImportError:
        print("[!] Missing dependencies. Please run: bash tools/setup_venv.sh")
        sys.exit(1)

    domain = input("Enter your Base Domain (default: hams.com): ").strip() or "hams.com"

    pwd = getpass.getpass("Enter NEW Odoo UI Admin password: ")
    pwd2 = getpass.getpass("Confirm Admin password: ")
    if pwd != pwd2 or not pwd:
        print("[!] Passwords do not match or are empty!")
        sys.exit(1)

    ctx = CryptContext(schemes=["pbkdf2_sha512"])
    hashed_admin_pwd = ctx.hash(pwd)

    cf_token = input("Enter Cloudflare Tunnel Token (leave blank to skip): ").strip()
    cf_api_token = getpass.getpass(
        "Enter Cloudflare API Token for Edge Cache/WAF (leave blank to skip): "
    ).strip()
    cf_zone_id = input("Enter Cloudflare Zone ID (leave blank to skip): ").strip()

    print("\n[*] Generating secure internal service credentials...")
    env_vars = {
        "DOMAIN": domain,
        "ODOO_ADMIN_PASSWORD": hashed_admin_pwd,
        "ODOO_SERVICE_PASSWORD": secrets.token_hex(24),
        "POSTGRES_DB": "hams_prod",
        "DB_NAME": "hams_prod",
        "POSTGRES_PASSWORD": secrets.token_hex(16),
        "RMQ_PASS": secrets.token_hex(16),
        "PDNS_API_KEY": secrets.token_hex(16),
        "HAMS_CRYPTO_KEY": Fernet.generate_key().decode("utf-8"),
        "DB_HOST": "postgres",  # Docker default, overridden in Debian class
        "REDIS_HOST": "redis",
        "RMQ_HOST": "rabbitmq",
        "ODOO_URL": "http://odoo:8069",
        "PDNS_API_URL": "http://127.0.0.1:8081",
    }
    env_vars["DB_PASS"] = env_vars["POSTGRES_PASSWORD"]

    if cf_token:
        env_vars["CLOUDFLARE_TUNNEL_TOKEN"] = cf_token
    if cf_api_token:
        env_vars["CLOUDFLARE_API_TOKEN"] = cf_api_token
    if cf_zone_id:
        env_vars["CLOUDFLARE_ZONE_ID"] = cf_zone_id

    os.makedirs(os.path.dirname(env_path), exist_ok=True)
    with open(env_path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by tools/deploy_wizard.py\n")
        for k, v in env_vars.items():
            f.write(f"{k}={v}\n")

    print("[+] Vault generated securely.\n")
    return env_vars


def scaffold_dummy_ssl(deploy_dir):
    """Generates self-signed certs so Nginx doesn't crash-loop on first boot."""
    ssl_dir = os.path.join(deploy_dir, "ssl")
    os.makedirs(ssl_dir, exist_ok=True)

    cert_path = os.path.join(ssl_dir, "fullchain.pem")
    key_path = os.path.join(ssl_dir, "privkey.pem")
    arrl_path = os.path.join(ssl_dir, "lotw_root.pem")

    if not os.path.exists(cert_path) or not os.path.exists(key_path):
        print(
            "[*] Generating fallback self-signed SSL certificates to ensure Nginx boots..."
        )
        subprocess.run(
            [
                "openssl",
                "req",
                "-x509",
                "-nodes",
                "-days",
                "3650",
                "-newkey",
                "rsa:2048",
                "-keyout",
                key_path,
                "-out",
                cert_path,
                "-subj",
                "/C=US/ST=CA/L=SF/O=Hams/CN=hams.local",
            ],
            check=True,
            stderr=subprocess.DEVNULL,
        )

    if not os.path.exists(arrl_path):
        print("[*] Scaffolding empty ARRL Root CA file...")
        with open(arrl_path, "w") as f:
            f.write(
                "-----BEGIN CERTIFICATE-----\n# Replace with actual ARRL Root CA\n-----END CERTIFICATE-----\n"
            )


class DebianDeployer:
    def __init__(self, repo_root, env_vars):
        self.repo_root = repo_root
        self.env_vars = env_vars
        # Override Docker defaults with local loopback for bare-metal
        self.env_vars["DB_HOST"] = "127.0.0.1"
        self.env_vars["REDIS_HOST"] = "127.0.0.1"
        self.env_vars["RMQ_HOST"] = "127.0.0.1"
        self.env_vars["ODOO_URL"] = "http://127.0.0.1:8069"

    def run_cmd(self, cmd, ignore_error=False, env=None):
        print(f"    $ {' '.join(cmd) if isinstance(cmd, list) else cmd}")
        try:
            subprocess.run(
                cmd, shell=isinstance(cmd, str), check=not ignore_error, env=env
            )
        except subprocess.CalledProcessError as e:
            if not ignore_error:
                print(f"    [!] Command failed: {e}")
                sys.exit(1)

    def step_apt(self):
        print("\n[*] Phase 1: Package Managers & Keys...")
        self.run_cmd(
            "wget -q -O - https://nightly.odoo.com/odoo.key | gpg --dearmor -o /usr/share/keyrings/odoo-archive-keyring.gpg --yes"
        )
        with open("/etc/apt/sources.list.d/odoo.list", "w") as f:
            f.write(
                "deb [signed-by=/usr/share/keyrings/odoo-archive-keyring.gpg] https://nightly.odoo.com/19.0/nightly/deb/ ./\n"
            )

        self.run_cmd(
            "curl -s https://kopia.io/signing-key | gpg --dearmor -o /usr/share/keyrings/kopia-keyring.gpg --yes"
        )
        with open("/etc/apt/sources.list.d/kopia.list", "w") as f:
            f.write(
                "deb [signed-by=/usr/share/keyrings/kopia-keyring.gpg] http://packages.kopia.io/apt/ stable main\n"
            )

        pkgs = [
            "postgresql-16",
            "postgresql-client",
            "postgresql-16-pgvector",
            "nginx",
            "redis-server",
            "rabbitmq-server",
            "python3-redis",
            "python3-pika",
            "sqlite3",
            "pdns-server",
            "pdns-backend-sqlite3",
            "odoo",
            "kopia",
            "pgbackrest",
            "certbot",
            "python3-certbot-nginx",
            "python3-venv",
            "build-essential",
            "libpq-dev",
            "python3-dev",
            "dnsutils",
        ]
        self.run_cmd(["apt-get", "update"])
        self.run_cmd(["apt-get", "install", "-y"] + pkgs)

    def step_postgres(self):
        print("\n[*] Phase 2: PostgreSQL Provisioning...")
        self.run_cmd(["systemctl", "enable", "--now", "postgresql"])
        self.run_cmd("sudo -u postgres createuser -s odoo || true", ignore_error=True)
        self.run_cmd(
            f"sudo -u postgres createdb -O odoo {self.env_vars['DB_NAME']} || true",
            ignore_error=True,
        )

    def step_odoo(self):
        print("\n[*] Phase 3: Odoo Application Environment...")
        self.run_cmd(
            "sed -i 's/; proxy_mode = False/proxy_mode = True/g' /etc/odoo/odoo.conf"
        )

        os.makedirs("/etc/systemd/system/odoo.service.d/", exist_ok=True)
        with open("/etc/systemd/system/odoo.service.d/override.conf", "w") as f:
            f.write("[Service]\n")
            f.write(
                f"Environment=\"ODOO_SERVICE_PASSWORD={self.env_vars.get('ODOO_SERVICE_PASSWORD')}\"\n"
            )
            f.write(
                f"Environment=\"CLOUDFLARE_API_TOKEN={self.env_vars.get('CLOUDFLARE_API_TOKEN', '')}\"\n"
            )
            f.write(
                f"Environment=\"CLOUDFLARE_ZONE_ID={self.env_vars.get('CLOUDFLARE_ZONE_ID', '')}\"\n"
            )

        addons_dir = "/usr/lib/python3/dist-packages/odoo/addons"
        for item in os.listdir(self.repo_root):
            item_path = os.path.join(self.repo_root, item)
            if os.path.isdir(item_path) and os.path.exists(
                os.path.join(item_path, "__manifest__.py")
            ):
                target = os.path.join(addons_dir, item)
                self.run_cmd(["ln", "-sf", item_path, target])
                self.run_cmd(["chown", "-h", "odoo:odoo", target])

        self.run_cmd(["systemctl", "daemon-reload"])
        self.run_cmd(["systemctl", "restart", "odoo"])
        self.run_cmd(["systemctl", "enable", "odoo"])

    def step_powerdns(self):
        print("\n[*] Phase 4: PowerDNS CQRS Architecture...")
        self.run_cmd(
            "sed -i 's/#DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf || true",
            ignore_error=True,
        )
        self.run_cmd("systemctl restart systemd-resolved || true", ignore_error=True)

        os.makedirs("/var/lib/powerdns", exist_ok=True)
        self.run_cmd(
            "sqlite3 /var/lib/powerdns/pdns.sqlite3 < /usr/share/doc/pdns-backend-sqlite3/schema.sqlite3.sql || true",
            ignore_error=True,
        )
        self.run_cmd(["chown", "-R", "pdns:pdns", "/var/lib/powerdns"])

        api_key = self.env_vars.get("PDNS_API_KEY", "secret")
        conf = f"""launch=gsqlite3
gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
gsqlite3-dnssec=no

api=yes
api-key={api_key}
webserver=yes
webserver-address=127.0.0.1
webserver-port=8081
webserver-allow-from=127.0.0.1
"""
        with open("/etc/powerdns/pdns.d/gsqlite3.conf", "w") as f:
            f.write(conf)

        if os.path.exists("/etc/powerdns/pdns.d/bind.conf"):
            os.remove("/etc/powerdns/pdns.d/bind.conf")

        self.run_cmd(["systemctl", "restart", "pdns"])
        self.run_cmd(["systemctl", "enable", "pdns"])

    def step_nginx(self):
        print("\n[*] Phase 5: Nginx Edge Router & mTLS...")
        nginx_conf_src = os.path.join(self.repo_root, "deploy", "nginx_hams.conf")
        target_conf = "/etc/nginx/sites-available/hams.com.conf"
        self.run_cmd(["cp", nginx_conf_src, target_conf])
        self.run_cmd(["ln", "-sf", target_conf, "/etc/nginx/sites-enabled/"])
        if os.path.exists("/etc/nginx/sites-enabled/default"):
            os.remove("/etc/nginx/sites-enabled/default")

        scaffold_dummy_ssl(os.path.join(self.repo_root, "deploy"))
        self.run_cmd(["mkdir", "-p", "/etc/nginx/ssl"])
        self.run_cmd(
            f"cp -r {self.repo_root}/deploy/ssl/* /etc/nginx/ssl/ || true",
            ignore_error=True,
        )

        self.run_cmd(["systemctl", "restart", "nginx"])
        self.run_cmd(["systemctl", "enable", "nginx"])

    def step_daemons(self):
        print("\n[*] Phase 6: Background Daemons & Orchestration...")
        with open("/etc/hams_daemons.env", "w") as f:
            for k, v in self.env_vars.items():
                f.write(f"{k}={v}\n")
        os.chmod("/etc/hams_daemons.env", 0o600)

        self.run_cmd(["bash", os.path.join(self.repo_root, "tools", "setup_venv.sh")])

        services = glob.glob(
            os.path.join(self.repo_root, "daemons", "**", "*.service"), recursive=True
        )
        timers = glob.glob(
            os.path.join(self.repo_root, "daemons", "**", "*.timer"), recursive=True
        )

        basenames = []
        for u in services + timers:
            base = os.path.basename(u)
            basenames.append(base)
            self.run_cmd(["ln", "-sf", u, f"/etc/systemd/system/{base}"])

        self.run_cmd(["systemctl", "daemon-reload"])
        for base in basenames:
            self.run_cmd(["systemctl", "enable", "--now", base])

    def step_cloudflared(self):
        token = self.env_vars.get("CLOUDFLARE_TUNNEL_TOKEN")
        if token:
            print("\n[*] Phase 7: Zero Trust Edge Tunnel...")
            self.run_cmd(
                "curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/download/2025.9.0/cloudflared-linux-amd64.deb"
            )
            self.run_cmd(
                "echo 'bbde50c639aecd7d1acf0edc4a3a434bbf1ffd985572277ea2671687727556c9  cloudflared.deb' | sha256sum -c -"
            )
            self.run_cmd(["dpkg", "-i", "cloudflared.deb"], ignore_error=True)
            if os.path.exists("cloudflared.deb"):
                os.remove("cloudflared.deb")
            self.run_cmd(
                ["cloudflared", "service", "install", token], ignore_error=True
            )

    def deploy(self):
        print("\n====================================================")
        print("  ⚙️ Initiating Idempotent Debian Deployment")
        print("====================================================\n")
        self.step_apt()
        self.step_postgres()
        self.step_odoo()
        self.step_powerdns()
        self.step_nginx()
        self.step_daemons()
        self.step_cloudflared()
        print(
            "\n✅ Bare-Metal Deployment Complete! All daemons are enabled and running."
        )


def main():
    auto_debian = "--auto-debian" in sys.argv

    print("====================================================")
    print("  🚀 Hams.com Unified Deployment & SRE Wizard  ")
    print("====================================================\n")

    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.abspath(os.path.join(script_dir, ".."))
    deploy_dir = os.path.join(repo_root, "deploy")
    env_path = os.path.join(deploy_dir, ".env")

    env_vars = {}
    if os.path.exists(env_path):
        print("[*] Found existing deployment state (.env).")
        if not auto_debian:
            use_existing = input("[?] Resume using this state? [Y/n]: ").strip().lower()
            if use_existing == "n":
                env_vars = prompt_and_generate(env_path)
            else:
                env_vars = load_existing_env(env_path)
        else:
            env_vars = load_existing_env(env_path)
    else:
        env_vars = prompt_and_generate(env_path)

    if auto_debian:
        choice = "2"
    else:
        print("\nHow would you like to deploy this node?")
        print("  [1] Docker Compose (Recommended - Isolated & Containerized)")
        print("  [2] Bare-Metal Debian (Direct OS Install)")
        print("  [3] Exit (I will start it manually later)")
        choice = input("Select an option [1-3]: ").strip()

    if choice == "1":
        scaffold_dummy_ssl(deploy_dir)
        print("\n[*] Orchestrating Docker Compose Build & Up...")
        os.chdir(deploy_dir)
        subprocess.run(["docker", "compose", "up", "-d", "--build"], check=True)
        print("\n✅ Deployment Complete! Hams.com is running via Docker.")
    elif choice == "2":
        if os.geteuid() != 0:
            print("\n[*] Debian Bare-Metal installation requires root privileges.")
            print("[*] Elevating to sudo...")
            os.execvp("sudo", ["sudo", sys.executable] + sys.argv + ["--auto-debian"])
        else:
            deployer = DebianDeployer(repo_root, env_vars)
            deployer.deploy()
    else:
        print(
            "\n[*] Setup saved. Run 'docker compose up -d' in the deploy/ directory when ready."
        )


if __name__ == "__main__":
    main()
