#!/usr/bin/env python3
import os
import sys
import getpass
import secrets

try:
    from passlib.context import CryptContext
    from cryptography.fernet import Fernet
except ImportError:
    print("[!] Missing dependencies. Please run: bash tools/setup_venv.sh")
    sys.exit(1)

def generate_fernet_key():
    """Generates a valid url-safe base64-encoded 32-byte key for At-Rest Encryption."""
    return Fernet.generate_key().decode('utf-8')

def generate_secret(length=32):
    """Generates a highly secure hex string for internal service authentication."""
    return secrets.token_hex(length // 2)

def main():
    print("====================================")
    print("  Hams.com Environment Initializer  ")
    print("====================================")
    
    # 1. User Inputs
    domain = input("Enter your Base Domain (default: hams.com): ").strip()
    if not domain:
        domain = "hams.com"

    pwd = getpass.getpass("Enter NEW Odoo UI Admin password: ")
    pwd2 = getpass.getpass("Confirm Admin password: ")
    if pwd != pwd2 or not pwd:
        print("[!] Passwords do not match or are empty!")
        sys.exit(1)
        
    ctx = CryptContext(schemes=["pbkdf2_sha512"])
    hashed_admin_pwd = ctx.hash(pwd)

    cf_token = input("Enter Cloudflare Tunnel Token (leave blank to skip): ").strip()
    cf_api_token = getpass.getpass("Enter Cloudflare API Token for Edge Cache/WAF (leave blank to skip): ").strip()
    cf_zone_id = input("Enter Cloudflare Zone ID (leave blank to skip): ").strip()
    gemini_key = getpass.getpass("Enter Gemini API Key for AI features (leave blank to skip): ").strip()

    print("\n[*] Pager Duty SMTP Fallback Settings (Optional but Highly Recommended)")
    fallback_email = input("Enter Fallback Alert Email: ").strip()
    smtp_host = input("Enter SMTP Host (e.g. smtp.gmail.com): ").strip()
    smtp_port = input("Enter SMTP Port (default: 587): ").strip() or "587"
    smtp_user = input("Enter SMTP User: ").strip()
    smtp_pass = getpass.getpass("Enter SMTP Password: ").strip()
    smtp_from = input("Enter SMTP From Address (default: pager-daemon@hams.com): ").strip() or "pager-daemon@hams.com"
    webhook_url = input("Enter Slack/Discord Webhook URL for ChatOps (leave blank to skip): ").strip()

    print("\n[*] DX Cluster Node Settings")
    dx_host = input("Enter DX Node Telnet Host (default: dxc.nc7j.com): ").strip() or "dxc.nc7j.com"
    dx_port = input("Enter DX Node Telnet Port (default: 7373): ").strip() or "7373"
    dx_call = input("Enter DX Node Login Callsign (default: N0CALL): ").strip() or "N0CALL"

    # 2. Generate Internal Secrets
    print("\n[*] Generating secure internal service credentials...")
    env_vars = {
        "DOMAIN": domain,
        "ODOO_ADMIN_PASSWORD": hashed_admin_pwd,
        "ODOO_SERVICE_PASSWORD": generate_secret(48),
        "POSTGRES_DB": "hams_prod",
        "DB_NAME": "hams_prod",
        "POSTGRES_PASSWORD": generate_secret(32),
        "RMQ_PASS": generate_secret(32),
        "PDNS_API_KEY": generate_secret(32),
        "HAMS_CRYPTO_KEY": generate_fernet_key(),
        "DB_HOST": "127.0.0.1",
        "REDIS_HOST": "127.0.0.1",
        "RMQ_HOST": "127.0.0.1",
        "ODOO_URL": "http://127.0.0.1:8069",
        "DX_NODE_HOST": dx_host,
        "DX_NODE_PORT": dx_port,
        "DX_NODE_CALLSIGN": dx_call,
        "PDNS_API_URL": "http://127.0.0.1:8081",
    }
    env_vars["DB_PASS"] = env_vars["POSTGRES_PASSWORD"]
    
    if cf_token:
        env_vars["CLOUDFLARE_TUNNEL_TOKEN"] = cf_token
    if cf_api_token:
        env_vars["CLOUDFLARE_API_TOKEN"] = cf_api_token
    if cf_zone_id:
        env_vars["CLOUDFLARE_ZONE_ID"] = cf_zone_id
    if gemini_key:
        env_vars["GEMINI_API_KEY"] = gemini_key
        env_vars["GEMINI_MODEL"] = "gemini-3.0-pro"

    if fallback_email and smtp_host:
        env_vars["PAGER_FALLBACK_EMAIL"] = fallback_email
        env_vars["SMTP_HOST"] = smtp_host
        env_vars["SMTP_PORT"] = smtp_port
        env_vars["SMTP_FROM"] = smtp_from
        if smtp_user: env_vars["SMTP_USER"] = smtp_user
        if smtp_pass: env_vars["SMTP_PASS"] = smtp_pass
    if webhook_url:
        env_vars["PAGER_WEBHOOK_URL"] = webhook_url

    # 3. Write to .env
    script_dir = os.path.dirname(os.path.abspath(__file__))
    env_path = os.path.abspath(os.path.join(script_dir, '..', 'deploy', '.env'))
    
    print(f"[*] Writing configuration to {env_path}...")
    os.makedirs(os.path.dirname(env_path), exist_ok=True)
    
    with open(env_path, 'w', encoding='utf-8') as f:
        f.write("# Auto-generated by tools/init_environment.py\n")
        for k, v in env_vars.items():
            f.write(f"{k}={v}\n")
            
    print("\n[+] Environment initialization complete!")
    print("[*] You can now safely run `docker compose up -d` or execute `install_debian.sh`.\n")

if __name__ == '__main__':
    main()
